const os = require('os')

console.log(os.EOL)
console.log(os.type())
console.log(os.release())
console.log(os.platform())
console.log(os.cpus().length)
console.log(os.arch())
console.log(os.endianness())
console.log(os.loadavg())
console.log(os.totalmem())
console.log(os.freemem())
console.log(os.uptime())
console.log(os.networkInterfaces())
console.log(os.hostname())
console.log(os.homedir())
console.log(os.tmpdir())